### ISSUE TITLE
AutoSizeText.rich not working well with maxLines

### ISSUE THREAD

**Issue by Koridev** [leisim/auto_size_text#8] opened 2019-03-26 20:54 UTC
The parameter `maxLines` doesn't work correctly with `AutoSizeText.rich`, it seems that the widget chose a size that would fit for the maximum number of lines in the space available, but then the result overflows if the `maxLines` parameter is lesser than this.

**Comment by leisim** [comment] 2019-03-27 08:15
I cannot reproduce this issue. Could you please provide a small sample?

**Comment by Koridev** [comment] 2019-03-27 09:45
I couldn't reproduce it outside of my project, and after trying your fix of [#7](https://github.com/leisim/auto_size_text/issues/7) and modifying my code accordingly this issue also got fixed.
It might have been due to a misuse on my part.

**Comment by leisim** [comment] 2019-03-27 09:49
Okay, let's close this issue for now. Please open it again if the problem happens again...

**Closed by leisim** 2019-03-27 09:49 UTC
