### ISSUE TITLE
Incorrect styling when using a theme switching toggle

### ISSUE THREAD

**Issue by mac6288** [leisim/auto_size_text#20] opened 2019-05-29 20:53 UTC
I'm writing an app for my workplace that has a light theme/dark theme toggle switch in a scaffold drawer. I've wrapped most of the text in the app with this widget for string length differences when localizing to other languages. Its been very helpful, but I'm finding that when i use the theme toggle the text colors aren't changing correctly. When loading a page in the app, the text is correctly contrasting against the background (black text on white BG and white text on grey BG) but once the theme toggle is activated the text then matches the background (black text on grey BG and white text on white BG). For reference, I've tried using this widget with two different theme toggling examples I've found online as a way to check if my implementation was causing the issue but its consistent with both of them.  The two examples I used can be found at the following github repos

https://github.com/jorgecoca/theme_switcher/tree/theme-switcher-tutorial-1
https://github.com/iampawan/Flutter-Dynamic-Theming

if i need to provide anymore information, please let me know.

**Comment by leisim** [comment] 2019-05-30 07:33
Thanks for reporting this issue.

The easiest way to check if it is a problem with this library is to replace the `AutoSizeText` with a `Text` if you still have the same problem it would help if you could provide a small sample.

Which version of `AutoSizeText` are you using?

**Comment by mac6288** [comment] 2019-05-30 13:32
I am using version 1.1.2 and i have confirmed that using a `Text` in place of an `AutoSizeText` works as expected. here is a code sample from on of the theme toggling methods i provided in the first note that replaces a `Text` with an `AutoSizeText` that reproduces my issue 


`import 'dart:async';

import 'package:auto_size_text/auto_size_text.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return StreamBuilder(
      stream: bloc.darkThemeEnabled,
      initialData: false,
      builder: (context, snapshot) => MaterialApp(
          theme: snapshot.data ? ThemeData.dark() : ThemeData.light(),
          home: HomePage(snapshot.data)),
    );
  }
}

class HomePage extends StatelessWidget {
  final bool darkThemeEnabled;

  HomePage(this.darkThemeEnabled);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Dynamic Theme"),
      ),
      body: Center(
        child: Text("Hello World"),
      ),
      drawer: Drawer(
        child: ListView(
          children: <Widget>[
            ListTile(
              title: AutoSizeText("Dark Theme"),
              trailing: Switch(
                value: darkThemeEnabled,
                onChanged: bloc.changeTheme,
              ),
            )
          ],
        ),
      ),
    );
  }
}

class Bloc {
  final _themeController = StreamController<bool>();
  get changeTheme => _themeController.sink.add;
  get darkThemeEnabled => _themeController.stream;
}

final bloc = Bloc();`

**Comment by mac6288** [comment] 2019-05-30 13:34
I am using version 1.1.2 and i have confirmed that using a `Text` in place of an `AutoSizeText` works as expected. here is a code sample from on of the theme toggling methods i provided in the first note that replaces a `Text` with an `AutoSizeText` that reproduces my issue

[main.txt](https://github.com/leisim/auto_size_text/files/3237195/main.txt)

**Comment by leisim** [comment] 2019-05-30 16:28
The problem is fixed in version `2.0.0-dev+2`. Could you please test if it works for you?

**Comment by mac6288** [comment] 2019-05-30 16:41
Looks like it's working on my end. I appreciate the quick turn around, Thanks!

**Closed** 2019-05-30 17:52 UTC
Labels: bug
